### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by Surftrader** [Surftrader/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by Slipixest** [comment]
Тильман Валентин (Тиль) Швайгер (нем. Tilman Valentin «Til» Schweiger; род. 19 декабря 1963, Фрайбург-им-Брайсгау) — немецкий актёр, кинорежиссёр, сценарист и продюсер.
