### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by Surftrader** [Surftrader/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by Slipixest** [comment]
Детство Тиля Швайгера прошло в Гисене. В 1977 году его семья переехала в Хойхельхайм (Гессен). Здесь он окончил школу со средним баллом «1,6» (В Германии «1» — отлично, «6» — неудовлетворительно). После окончания школы Тиль пошёл по стопам родителей и поступил на факультет германистики, однако вскоре бросил учёбу. Позднее решил посвятить себя медицине, но и эта попытка не увенчалась успехом. Подруга, учившаяся в театральной школе, убедила Тиля в том, что он обладает выдающимся актёрским талантом, и сподвигла его на поступление в театральную школу в Кёльне под названием Der Keller («Подвал»), которую он успешно окончил через три с половиной года.

Карьера началась с небольшой роли в сериале «Линденштрассе». Затем он работал синхронистом, озвучивая разные фильмы, в том числе и фильмы категории ХХХ.

В 1989 году он был приглашён на работу в театр «Контра-Крайс» (нем. Contra-Kreis-Theater) в Бонне.

Мировую славу актёру принёс фильм «Достучаться до небес» («Knockin' on Heaven’s Door»), за который он был удостоен премии Московского кинофестиваля 1997 года за лучшую мужскую роль.
