### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by Surftrader** [Surftrader/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by Slipixest** [comment]
19 июня 1995 года Тиль Швайгер женился на бывшей модели, американке Дэне Карлсен. Семья жила в США до 2004 года, потом они переехали в Гамбург и поселились на вилле, выполненной в английском стиле. С 2005 года живут раздельно. У супругов четверо детей: Валентин Флориан (род. 1995 год), Луна Мари (род. 11 января 1997 год), Лилли Камиль (род. 1998 год), Эмма Тигер (род. 26 октября 2002 год). Они уже снимались в фильмах отца: например, в «Красавчике» можно увидеть всех четверых. Тиль Швайгер развёлся в 2009 году, но, по его утверждению, это никак не отразилось на его детях. С 2013 года, Швайгер также был замечен в различных рекламных фильмах с его дочерьми[1].
